services:
  linux:
    image: ubuntu:latest
    container_name: linux
    environment:
      - USERNAME=flare
      - PASSWORD=123456@
    tty: true
    stdin_open: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "8006:8006"
      - "3389:3389"
    volumes:
      - linux-data:/home/flare
    stop_grace_period: 2m

volumes:
  linux-data: